### ISSUE TITLE
Alpha feature bug: using any rgb/rgba/hsl/hsla values in 'allowedCols' results in multiple swatches created

### ISSUE THREAD

**Issue by daattali** [daattali/colourpicker#14]
For example:

```
colourInput("col", "colour", "yellow", palette = "limited",
  allowedCols = c("red", "yellow", "rgb(0, 0, 255)"))
```

creates a few empty wrong swatches

![image](https://user-images.githubusercontent.com/952340/27525120-13f8df36-5a09-11e7-93c6-33e85c5118f6.png)

@DavidRGriswold perhaps you know something about this?

**Comment by DavidRGriswold** [comment]
I will be able to look into this today.

**Comment by daattali** [comment]
It's solved, thanks! (Haven't pushed yet)
