### ISSUE TITLE
consider adding a warning to colourInput for reverting unsupported color

### ISSUE THREAD

**Issue by romunov** [daattali/colourpicker#22]
If `palette = "limited`" is selected and specified color is not in the (limited) list, it will revert to black. Would it possible to add a warning that the function has reverted to some prespecified color?

**Comment by daattali** [comment]
I don't think it's that bad of a behaviour. I wonder what happens if you create a `selectInput()` or radio buttons and provide a non-existent value? Anyway, I'm open to a PR if you'd like to add a simple error check for that

**Comment by romunov** [comment]
I was thinking alongside of a `warning`, just to give tinkerer a head's up. Or perhaps a sentence about this in the docs. I would consider falling back to some predefined color as perfectly acceptable.
