### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by 905168041** [daattali/colourpicker#26]
When I install muxViz, I do the step library(colourpicker), why there is a error message: colourInput() has been moved to the 'colourpicker' package.

**Comment by daattali** [comment]
I'm not sure what muxViz is, but that error is an error that comes from the shinyjs package. The `colourInput()` function used to be in the `shinyjs` package but it has moved into the `colourpicker` package. So when you get that error, it sounds like you're trying (directly or indirectly) to use the `colourInput()` function from shinyjs.

**Comment by 905168041** [comment]
I'm following the step to test this function
library(shiny)
shinyApp(
    ui = fluidPage(
        colourInput("col", "Select colour", "purple"),
        plotOutput("plot")
    ),
    server = function(input, output) {
        output$plot <- renderPlot({
            set.seed(1)
            plot(rnorm(50), bg = input$col, col = input$col, pch = 21)
        })
    }
)
it also have the same error:colourInput() has been moved to the 'colourpicker' package.
When I try library(colourpicker) at first, it will run normal.
But when I install muxViz I do   library(colourpicker)  at first, it can't solve the error.
I don't konw what can I do next.

**Comment by daattali** [comment]
The error you are getting is because it's trying to use the function from the shinyjs package. If you restart your R session, running your code will not work because neither shinyjs nor colourpicker packages are loaded. If you load colourpicker and then the code that you pasted, you will have no problem. If instead you load shinyjs and then the code you pasted, you'll see the error.

Again, I don't know what muxViz is, but it sounds like perhaps it's using an old version of shinyjs, and they should be using colourpicker instead.

**Comment by 905168041** [comment]
Ok, thanks for your help. My English is not good. If I have some mistake in language, hopes for forgive.

**Comment by daattali** [comment]
I informed muxViz about this error, they should be able to fix it on their end.

**Comment by 905168041** [comment]
Thank you

**Comment by sugargon** [comment]
muxViz hasn't fixed the problem but you can solve it by changing the following sections in the R scripts:
In the unzipped file "muxViz-master", open "muxVizGUI.R" and add the following on line 90: 
```
if(!require(colourpicker)){
  install.packages("colourpicker")
}
```
Also, open "ui.R" and find & replace `shinyjs::colourInput` with `colourpicker::colourInput`

save the edits, then run again `source('muxVizGUI.R')`

**Comment by daattali** [comment]
thank you @sugargon

**Comment by daattali** [comment]
reference to issue on muxviz: https://github.com/manlius/muxViz/issues/5

**Comment by salmanahmed84** [comment]
Hi, I am using RtutoR package for EDA. 
While using the shiny dashboard, Just after clicking the aesthetics section, generating below error and nothing works.
Facing same problem "Warning: Error in : colourInput() has been moved to the 'colourpicker' package."

I have installed the latest version of colourpicker, still same issue. Any idea how to sort this?

Thanks
