### ISSUE TITLE
Feature Request::Eyedropper for choosing a color

### ISSUE THREAD

**Issue by jdgagnon** [daattali/colourpicker#29]

**Comment by daattali** [comment]
That's not really in the scope of a colour picker widget. Eye dropper is a n entirely different beast, doing eyedropper functionality is not really an easy (or even doable?) thing to do with javascript. See this question on stackoverflow https://stackoverflow.com/questions/1936021/javascript-eyedropper-tell-color-of-pixel-under-mouse-cursor
