### ISSUE TITLE
FR: Use keyboard to navigate the colour picker

### ISSUE THREAD

**Issue by johnpauls** [daattali/colourpicker#3]
This is a great utility - thanks for creating it!

I would like to request adding keyboard navigation to the colour picker so that is can be more accessible for folks who can't use the mouse.

**Comment by daattali** [comment]
Great timing. I'm in the process of adding a really cool feature: a plot
colour helper, where you enter the code for a plot, and you can
interactively change the colours with the colouepicker. And I did in fact
add a bunch of keyboard shortcuts to it (add colour, remove colour, move to
previous and next, and 1-9 select the first to ninth colour). I haven't
added those features yet to the colour picker (they're currently only in
the plot helper), but I will before the next cran release. Try out the plot
helper if you want to see the keyboard shortcuts :)

**Comment by daattali** [comment]
this feature is now available in the dev version

**Comment by johnpauls** [comment]
Thanks for adding this so quickly. I just had a chance to try it out, both as a `colourInput()` in a shiny app and as a `colourPicker()` from the console, I can't change the individual colors. With `colourPicker` I can select the colors 1-9, add or remove colors, but I cannot change what each color is. Am I missing something? Or is this a separate issue?

**Comment by daattali** [comment]
The keyboard shortcuts are for navigating between the colours  (as the
issue title says!), but not for setting a colour. How were you hoping to do
that? I'm not even sure what the user interaction for that would look like

**Comment by johnpauls** [comment]
Sorry, I guess I was not very clear. I was envisioning something whereby once you got to the interface where you set the colors, for either`colourInput` or `colourPicker` you would use the arrow keys to move the black dot and then enter would select the color. As for the white line on the side, that could be operated either by tabbing over to it and using arrow keys, or alternatively the PageUp and PageDown could be used to move it up and down.   That said, I don't know JavaScript so I have no idea how feasible such a mechanism would be.  

Either way, thanks for making colourPicker, it is a really great package!

**Comment by daattali** [comment]
Oh I understand what you mean. Sorry, that's a bit strange to implement. If
you ever pick up javascript and feel adventurous and figure out a nice way
to implement this in a way that makes sense, then I'd welcome a PR. But
otherwise, I don't think I'm going to add that, sorry!
