### ISSUE TITLE
Feature Request:: Ability to have both a list of preset colors and the ability to choose any color (even if not in the preset list)

### ISSUE THREAD

**Issue by jdgagnon** [daattali/colourpicker#30]

**Comment by daattali** [comment]
I'm not against this idea in theory, but it would require 1. designing the UI and UX of how this functionality would work, and 2. substantive work on [the javascript library](https://github.com/daattali/jquery-colourpicker). I'm very happy with the current featureset and I don't see myself having time to work on this but if someone wants to help out I'd be happy to merge!

**Comment by jdgagnon** [comment]
Ah, sounds like a lot more work than I had thought. Was hoping it would be as easy as doubling up the colourInput() call and converging the inputs somehow. I don't know any javascript so I guess I'll just have to hope for someone else with the expertise and the motivation to come along.

Love your `colourpicker` package!

**Comment by daattali** [comment]
I don't think this will ever be implemented, so I'm closing the issue. If someone ever wants to submit a PR for this, it would be welcomed but I doubt someone else will take this upon themselves :)
