### ISSUE TITLE
Feature request: Support for restore state in Shiny

### ISSUE THREAD

**Issue by ohjakobsen** [daattali/colourpicker#32]
Colourpicker is an amazing tool for Shiny development, but would be even better if it supported the bookmarking feature in `shiny`. This will probably be easily implemented by adding `value <- restoreInput(id = inputId, default = value)` to `colorInput.R`.

**Comment by daattali** [comment]
Good idea! Feel free to submit a PR after making sure that works

**Comment by ohjakobsen** [comment]
Added PR #33

**Comment by daattali** [comment]
fixed
