### ISSUE TITLE
close on click

### ISSUE THREAD

**Issue by ghost** [daattali/colourpicker#34]
I think it would be a big improvement if there is the option to close the colourinput on click / selection instead of having to click outside the dropdown

**Comment by daattali** [comment]
This is something that would need to be implemented in the javascript library, not in shiny.  Could you open this request in https://github.com/daattali/jquery-colourpicker please

**Comment by daattali** [comment]
this is now supported

**Comment by ghost** [comment]
Cool! I noticed it is currently still only in the github version, as I got errors when installing all my packages on a new laptop, but I guess it will become part of the cran version sooner or later. Thanks Dean

**Comment by daattali** [comment]
I really should submit to CRAN already. Will do soon
