### ISSUE TITLE
_R_CHECK_LENGTH_1_LOGIC2_

### ISSUE THREAD

**Issue by bastistician** [daattali/colourpicker#39]
With enabled environment variable `_R_CHECK_LENGTH_1_LOGIC2_`, the **colourpicker** addin cannot be used. The error is
```
Error in !is.null(y) && !is.na(y) : 
  'length(x) = 3 > 1' in coercion to 'logical(1)'
```
from `%AND%`. See https://github.com/rstudio/shiny/commit/d7d8e78e420ba510667d102493aeaf16c30497c0 for how to fix this.

**Comment by daattali** [comment]
Thanks for pointing this out!
