### ISSUE TITLE
colourInput fails if color passed to 'value' contains alpha.

### ISSUE THREAD

**Issue by ddiez** [daattali/colourpicker#4]
This throws an error:

```
library(shiny)
library(colourpicker)
shinyApp(
  ui = fluidPage(
    strong("Selected colour:", textOutput("value", inline = TRUE)),
    colourInput("col", "Choose colour", "#FF0000FF"),
    h3("Update colour input"),
    textInput("text", "New colour: (colour name or HEX value)"),
    selectInput("showColour", "Show colour",
                c("both", "text", "background")),
    selectInput("palette", "Colour palette",
                c("square", "limited")),
    checkboxInput("allowTransparent", "Allow transparent", FALSE),
    checkboxInput("returnName", "Return R colour name", FALSE),
    actionButton("btn", "Update")
  ),
  server = function(input, output, session) {
    observeEvent(input$btn, {
      updateColourInput(session, "col",
                        value = input$text, showColour = input$showColour,
                        allowTransparent = input$allowTransparent,
                        palette = input$palette,
                        returnName = input$returnName)
    })
    output$value <- renderText(input$col)
  }
)

Error: #FF0000FF is not a valid colour
```
Not sure if possible/easy to add ability to set alpha. Alternatively, could drop alpha information instead of error? Function viridis() returns colors this way. Of course I can remove the information myself but wondering whether it would be better handled directly here.

**Comment by daattali** [comment]
The colourpicker does not have support for alpha values. I was briefly considering it 1.5 years ago, but seeing as there was a lack of interest in supporting that and I couldn't think of a great UI/interaction for it, I just left it.

If you know javascript and have a bit of time and feeling adventurous, I would very happily accept a PR - the bulk of the work to add support for this would have to be done to [the javascript library](https://github.com/daattali/jquery-colourpicker). Once the JS supports it, adding it to R is a breeze. Unfortunately I myself don't have the bandwidth for this anytime soon!

Alternatively, I'd also welcome a PR that throws a warning or a message when a alpha-containing colour is passed into the colourpicker and returns the colour without the alpha

**Comment by ddiez** [comment]
Thanks for the quick reply! Don't know enough JS to feel adventurous but will consider the PR for the warning option.

**Comment by daattali** [comment]
Cool. Just make sure it's robust enough to work for all sorts of cases - updating a colour, providing too many digits, providing a wrong HEX code, lower case or upper case, etc. The existing code should already take care of most of that. Thanks!
