### ISSUE TITLE
colourInput() has been moved to the 'colourpicker' package

### ISSUE THREAD

**Issue by salmanahmed84** [daattali/colourpicker#47]
Hi,

While using some packages e.g. rtutoR, I am facing below warning and after that the package stops working(do not plot anything)

Warning: Error in : colourInput() has been moved to the 'colourpicker' package.
  111: <Anonymous>
Warning: Error in if: argument is of length zero
  [No stack trace available]

Somehow it is referencing ColorInput, however colourpicker is installed and loaded just before running the rtutoR package
In another thread, it was mentioned that colourpicker 1.2 on github works but 1.1.1.9 is one available on github

https://github.com/jforbes14/eechidna/issues/18

**Comment by daattali** [comment]
That sounds like an issue with the package you're using, not with colourpicker. You should contact the author of that package and let them know about the error, they need to update their internal calls to colourInput to use the colourpicker package.
