### ISSUE TITLE
Use colourInput() to select multiple colours

### ISSUE THREAD

**Issue by limbo1996** [daattali/colourpicker#49]
Hello
The colourpicker tool is a great package. I was wondering do you plan to introduce choosing multiple colours use `colourInput()`? I want to choose multiple  colours  in my shiny app.But but I noticed that colourInput() doesn't have a multi-select parameter like `selectInput()`

Thank you.

**Comment by daattali** [comment]
I've thought about this in the past but I could never even come up with a good idea of visually and practically what that would look like. It would obviously have to work in tandem with all other parameters and be very clear in how it works and how the output is shown. If after spending some time thinking about it you can come up with a good design, I could start looking at how feasible it is to implement.

**Comment by daattali** [comment]
Closing this because I don't relastically see it happening. I'd be happy to re-discuss if anyone has good ideas in the future

**Comment by j-andrews7** [comment]
For what it's worth, we have an input that implements this in [VizModules](https://j-andrews7.github.io/VizModules/articles/custom-shiny-inputs.html#multicolorpicker).


It looks like so:
<img width="276" height="283" alt="Image" src="https://github.com/user-attachments/assets/7a93d79f-0d9b-42f9-9933-504d4923e5c7" />
