### ISSUE TITLE
Put colourInput() to the front

### ISSUE THREAD

**Issue by gaospecial** [daattali/colourpicker#57]
Dear developer, I have an issue of the display of color picker in Shiny app (<https://bio-spring.shinyapps.io/ggVennDiagram/>). When I open the color palette, it is masked by the main card.

<img width="431" alt="image" src="https://github.com/daattali/colourpicker/assets/107597/1d209fbe-4ec6-4ca2-808e-2769359af237">

I tried to fix this by change the CSS style of the popup menu. But it doesn't work.

Could you give me any suggestions?

**Comment by daattali** [comment]
It looks like this isn't an issue with the colourpicker, it's the sidebar of that page. Anything you place in that sidebar that goes beyond the right side will just cause a horizontal scrollbar. You can see in my screenshot:

![image](https://github.com/daattali/colourpicker/assets/952340/6e23d357-a646-49e9-8c01-3b922575373f)

The author of that shiny app can try to fix it by playing with the sidebar's css, but I think the better solution is to make the colour input wider (it's very short right now), which would let the popup box be more to the left
