### ISSUE TITLE
Rmarkdown 

### ISSUE THREAD

**Issue by Tpatni123** [daattali/colourpicker#59]
Hi,
Thank you so much for the package! 
I was wondering if we could use the colourpicker package in Rmarkdown and provide the flexibility of choosing different colors for the plots in the HTML output of Rmarkdown document.

**Comment by daattali** [comment]
Yes, you can use `colourpicker::colourInput()` in a Rmarkdown (or quarto) document, no problem. You cannot use the RStudio Addin however.

**Comment by Tpatni123** [comment]
Hi, 
In this example, can you please help me as to how I can use the ```colourpicker::colourInput()``` function in the ```color``` aesthetic argument and knit the rmd document?
![image](https://github.com/user-attachments/assets/e39cbc4c-d844-4598-9871-80d346d5dd2d)
Thanks in advance for the help!

**Comment by daattali** [comment]
There's nothing "special" about this package, it works just like any other shiny input. To use shiny inputs in rmd, you must utilize the `runtime: shiny` engine. Here's an example:

````
---
title: "Untitled"
output: html_document
date: "2024-12-13"
runtime: shiny
---

```{r}
library(ggplot2)
library(shiny)
colourpicker::colourInput("col", "Select colour", value = "steelblue")
renderPlot({
  ggplot(mtcars, aes(x = wt, y = mpg)) +  geom_point(size = 4, color = input$col)
})
```
````
